### PR TITLE
Added max width to the post component

### PR DESCRIPTION
**Pull request by Jaccident2910**
This is to fix [issue #18](https://github.com/vivlim/pillbug/issues/18). There is a set of utilities in tailwind CSS that allow you to set the maximum width of a component, and I used `max-w-4xl` as it looked good on my computer.

I am not particularly experienced with git so I hope I've done everything correctly!

### CODE REVIEW

**Comment by vivlim** [comment]
Thanks for the PR! I tried this and noticed that the post column doesn't get centered, which is more apparent on an ultrawide display:
image

As well I think it'd be better to set the max width at the navigation frame level so that other views like the notification list would also not span the full width. I think the main places to fiddle with are around `facetnavigation.tsx:81` and `facetnavigation.tsx:124`. From briefly poking around my browser's dev tools it seems like `flex-grow` *may* need to be removed, it might not be necessary in those spots.

**Comment by Jaccident2910** [comment]
Right so I got a little confused by how PRs work in github but it should all be working now! I changed the max width to apply to the container for the main content at `facetNavigation.tsx:125`, and then used auto margins to "centre" the main content on the screen. I couldn't figure out how to get it into the actual centre, but it should be vaguely centred in all monitor configurations now.  Please could you give it another test and see if you're happy with it?

**Comment by vivlim** [comment]
> Right so I got a little confused by how PRs work in github but it should all be working now!

No worries, I don't mind. This is as good a place as any to get some practice with the github fork pull request workflow 👍

The feed's looking pretty good, but the navigation buttons look a bit lonely stuck all the way to the side:
image

One option for fixing this is to add a `<div class="flex flex-grow"/>` on each side:
image
If you take that approach, it'd probably be good to remove the `gap-4` from the enclosing div, otherwise it introduces a margin on the left and right side on mobile.

I noticed the pop-up nav now floats in the middle, that's not the end of the world but I'd prefer it to be still stuck to the left side.
image
Removing `justify-center` seems to fix it, though I didn't look too carefully.

**Comment by snowkat** [comment]
You could also get away with removing the `mr-auto` class on the inner divs and relying on `justify-center` on the outer div to keep everything in the center. That'd avoid the need for extra div elements.

**Comment by Jaccident2910** [comment]
So it turns out I had overcomplicated things - I thought the notifications were supposed to stay at the side. I added the `md` prefix to the `justify-center` to ensure it only happens when we aren't displaying on mobile, and removed all the margin silliness. Thanks for bearing with me with all this, this was probably much more work than was necessary.

**Review by vivlim — APPROVED** [review]
looks good- thanks for taking the time to fiddle with this!

**Pull request merged**
