### PR TITLE
AvatarLink excess height fixed

### LINKED ISSUE #37: avatars to the side of posts have an oversized hitbox
As shown, clicking anywhere in the highlighted region links to the user's profile.
Screenshot 2024-10-09 at 22 24 39

`<AvatarImage>` and `<AvatarLink>` possibly want restructuring? `<AvatarLink>` wraps an `<a>` around an `<AvatarImage>`, but inherits its own size from the parent element, causing the above.

### PR DESCRIPTION
**Pull request by JTrunov**
This change resolves #37 by adding max-h-max classname

### CODE REVIEW

**Comment by lunasorcery** [comment]
Either I've missed something or this doesn't resolve the issue, the hitboxes are still giant:
Screenshot 2024-10-10 at 18 09 13

**Comment by JTrunov** [comment]
That's strange, in Chrome it looks fine. Which browser do you use?
image

**Comment by lunasorcery** [comment]
How strange! — I'm on Firefox 131.0.2 on macOS

**Comment by JTrunov** [comment]
I tried it in Firefox, got the same result as you. I will try to find a workaround for it. Can you assign me to this issue?

**Comment by lunasorcery** [comment]
Alas, I don't have the power to assign things.

I'm almost wondering if the more sensible solution might be to have the `<a>` tag be dictating the size/shape of the avatar in the same manner the `<div>` in `<AvatarImage>` currently does, perhaps entirely replacing the `<div>` with a corresponding `<a>` when there's a link, but I'm not familiar enough with this component stuff to see a clean way to do that.

**Review by vivlim — APPROVED** [review]
lgtm, i tried it on firefox 131.0.2

**Pull request merged**
